name: harmoni
description: "Mood tracking app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  dio: ^5.7.0
  go_router: ^14.6.3
  get_it: ^8.0.3
  intl: ^0.20.1
  json_annotation: ^4.9.0
  yaml: ^3.1.3
  animate_do: ^3.3.4
  gap: ^3.0.1
  drift: ^2.23.1
  postgres: ^3.4.8
  drift_postgres: ^1.3.0
  flutter_animate: ^4.5.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.2
  drift_dev: ^2.23.1

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/emoji/
    - assets/emoji/toon_pack/
    - assets/emoji/kawai_pack/
    - assets/emoji/simple_pack/
    - assets/emoji/halloween_pack/
    - assets/emoji/cubit_pack/
    - assets/emoji/shiny_pack/
    - assets/emoji/simple_2_pack/
    - assets/emoji/expresive_pack/
    - assets/emoji/base_simple_pack/
    - assets/emoji/cube_simple_pack/
    - assets/images/
